tasks:
    - name: download software/binaries
      init: |
        # create directory "bin" to download all your binaries
        mkdir -p /workspace/bin
        # enter into "bin directory"
        cd /workspace/bin
        
        ################### MUSCLE
        # download muscle
        wget https://github.com/rcedgar/muscle/releases/download/5.1.0/muscle5.1.linux_intel64
        # rename downloaded binary
        mv muscle5.1.linux_intel64 muscle
        # make the binary executable
        chmod u+x muscle
        # check if it works
        ./muscle

        ################### FastTree
        # download FastTree
        wget http://www.microbesonline.org/fasttree/FastTree
        # make the binary executable
        chmod u+x FastTree
        # check if it works
        ./FastTree

        ################### Clustal Omega
        # download Clustal Omega
        wget http://www.clustal.org/omega/clustalo-1.2.4-Ubuntu-x86_64
        # rename downloaded binary
        mv clustalo-1.2.4-Ubuntu-x86_64 clustalo
        # make the binary executable
        chmod u+x clustalo
        # check if it works
        ./clustalo --version

        ################### MrBayes
        # install brew
        NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        # install MrBayes
        brew reinstall -s mrbayes
        brew reinstall -s beagle

    - name: clear terminal
      command: |
        clear

vscode:
    extensions:
        # enable pdf files for viewing in VS Code
        - anwar.papyrus-pdf

github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for all branches in this repo (defaults to false)
        branches: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
        # enable for pull requests coming from forks (defaults to false)
        pullRequestsFromForks: true
        # configure whether Gitpod registers itself as a status check to pull requests
        addCheck: false
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
        addComment: false
        # add a "Review in Gitpod" button to pull requests (defaults to false)
        addBadge: true

workspaceLocation: "/workspace"
