vscode:
    extensions:
    # enable pdf files for viewing in VS Code
    - anwar.papyrus-pdf

github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for all branches in this repo (defaults to false)
        branches: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
        # enable for pull requests coming from forks (defaults to false)
        pullRequestsFromForks: true
        # configure whether Gitpod registers itself as a status check to pull requests
        addCheck: false
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
        addComment: false
        # add a "Review in Gitpod" button to pull requests (defaults to false)
        addBadge: true
