tasks:
    - name: download software/binaries
      init: |
        # create directory "bin" to download all your binaries
        mkdir -p /workspace/bin
        # enter into "bin directory"
        cd /workspace/bin
        # download muscle
        wget https://github.com/rcedgar/muscle/releases/download/5.1.0/muscle5.1.linux_intel64
        # rename downloaded binary
        mv muscle5.1.linux_intel64 muscle
        # make the binary executable
        chmod u+x muscle
        # check if it works
        ./muscle
    - name: source bash configurations
      command: |
        source /workspace/gene-tree-workshop/.bash-workshop
    - name: clear terminal
      command: |
        clear

vscode:
    extensions:
        # enable pdf files for viewing in VS Code
        - anwar.papyrus-pdf

github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for all branches in this repo (defaults to false)
        branches: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
        # enable for pull requests coming from forks (defaults to false)
        pullRequestsFromForks: true
        # configure whether Gitpod registers itself as a status check to pull requests
        addCheck: false
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
        addComment: false
        # add a "Review in Gitpod" button to pull requests (defaults to false)
        addBadge: true

workspaceLocation: "/workspace"
